### PR TITLE
changed path to karma bin: solve ENOENT error

### PR DESCRIPTION
**Pull request by djhi**
I had this error which prevented client unit tests to run:
```
W20141217-10:16:53.161(-5)? (STDERR) events.js:72
W20141217-10:16:53.162(-5)? (STDERR) throw er; // Unhandled 'error' event
W20141217-10:16:53.162(-5)? (STDERR) ^
W20141217-10:16:53.166(-5)? (STDERR) Error: spawn ENOENT
W20141217-10:16:53.167(-5)? (STDERR) at errnoException (child_process.js:1000:11)
W20141217-10:16:53.167(-5)? (STDERR) at Process.ChildProcess._handle.onexit (child_process.js:791:34)
```

### CODE REVIEW

**Comment by Sanjo** [comment]
What operation system do you use and what Meteor version? On Mac OS X it's still a `:` for me. Maybe it's inconsistent.

**Comment by Sanjo** [comment]
Ok, in the devel version of Meteor Core, I also get the error.

**Comment by djhi** [comment]
Right, I should have mentionned that. I'm on linux 64 and I use the 1.0.4
release of Meteor.

**Comment by Sanjo** [comment]
Fixed via https://github.com/Sanjo/meteor-karma/commit/c2835c71d169295956c37caaf0bb714c3cf18a90.

**Pull request closed without merging**
